# Generated by Django 4.1.4 on 2022-12-29 07:52

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True)),
                ('keywords', models.CharField(max_length=255)),
                ('content', ckeditor.fields.RichTextField()),
            ],
        ),
    ]
