# Generated by Django 4.1.4 on 2022-12-29 13:34

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_post_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'verbose_name': '文章', 'verbose_name_plural': '文章'},
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=ckeditor.fields.RichTextField(verbose_name='文章内容'),
        ),
        migrations.AlterField(
            model_name='post',
            name='description',
            field=models.TextField(blank=True, verbose_name='文章描述'),
        ),
        migrations.AlterField(
            model_name='post',
            name='keywords',
            field=models.CharField(help_text='多个关键词使用","分割', max_length=255, verbose_name='关键字'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=64, verbose_name='文章标题'),
        ),
    ]
