# Generated by Django 4.1.4 on 2022-12-29 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_alter_post_options_alter_post_content_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='keywords',
            field=models.CharField(db_column='keywords', help_text='多个关键词使用","分割', max_length=255, verbose_name='关键字'),
        ),
    ]
