# Generated by Django 4.1.4 on 2022-12-29 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_alter_post_keywords'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='keywords',
            field=models.CharField(help_text='多个关键词使用","分割', max_length=255, verbose_name='关键字'),
        ),
    ]
